version: '3.8'

services:
  producer:
    build: ./producer
    environment:
      - SERVER_PORT=8080
    ports:
      - "8080:8080"
    depends_on:
      - kafka

  consumer:
    build: ./consumer
    environment:
      - SERVER_PORT=8081
    ports:
      - "8081:8081"
    depends_on:
      - kafka

  security:
    build: ./security
    environment:
      - SERVER_PORT=8082
    ports:
      - "8082:8082"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "my-topic:1:1"
    depends_on:
      - zookeeper

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
