INSERT INTO ROL(ID_ROL,DESCRIPTION) values (NEXTVAL('rol_seq'),'ADMIN')
INSERT INTO USER_EVENT (ID_USER,PASSWORD,USER_NAME) VALUES (NEXTVAL('user_seq'),'$2y$10$gMrvLFF5SwqtLt/9KGLjFOrrm0Z7yxuydMWT/Xs6YnBTOeRuaC5ZG','admin@gmail.com')
INSERT INTO USER_ROL(ID_ROL,ID_USER) VALUES (CURRVAL('rol_seq'),CURRVAL('user_seq'));
--password admin